/*
Copyright 2024 nineinfra.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/nineinfra/hdfs-operator/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHdfsClusters implements HdfsClusterInterface
type FakeHdfsClusters struct {
	Fake *FakeHdfsV1
	ns   string
}

var hdfsclustersResource = v1.SchemeGroupVersion.WithResource("hdfsclusters")

var hdfsclustersKind = v1.SchemeGroupVersion.WithKind("HdfsCluster")

// Get takes name of the hdfsCluster, and returns the corresponding hdfsCluster object, and an error if there is any.
func (c *FakeHdfsClusters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hdfsclustersResource, c.ns, name), &v1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HdfsCluster), err
}

// List takes label and field selectors, and returns the list of HdfsClusters that match those selectors.
func (c *FakeHdfsClusters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.HdfsClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hdfsclustersResource, hdfsclustersKind, c.ns, opts), &v1.HdfsClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.HdfsClusterList{ListMeta: obj.(*v1.HdfsClusterList).ListMeta}
	for _, item := range obj.(*v1.HdfsClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hdfsClusters.
func (c *FakeHdfsClusters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hdfsclustersResource, c.ns, opts))

}

// Create takes the representation of a hdfsCluster and creates it.  Returns the server's representation of the hdfsCluster, and an error, if there is any.
func (c *FakeHdfsClusters) Create(ctx context.Context, hdfsCluster *v1.HdfsCluster, opts metav1.CreateOptions) (result *v1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hdfsclustersResource, c.ns, hdfsCluster), &v1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HdfsCluster), err
}

// Update takes the representation of a hdfsCluster and updates it. Returns the server's representation of the hdfsCluster, and an error, if there is any.
func (c *FakeHdfsClusters) Update(ctx context.Context, hdfsCluster *v1.HdfsCluster, opts metav1.UpdateOptions) (result *v1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hdfsclustersResource, c.ns, hdfsCluster), &v1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HdfsCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHdfsClusters) UpdateStatus(ctx context.Context, hdfsCluster *v1.HdfsCluster, opts metav1.UpdateOptions) (*v1.HdfsCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hdfsclustersResource, "status", c.ns, hdfsCluster), &v1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HdfsCluster), err
}

// Delete takes name of the hdfsCluster and deletes it. Returns an error if one occurs.
func (c *FakeHdfsClusters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hdfsclustersResource, c.ns, name, opts), &v1.HdfsCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHdfsClusters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hdfsclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.HdfsClusterList{})
	return err
}

// Patch applies the patch and returns the patched hdfsCluster.
func (c *FakeHdfsClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.HdfsCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hdfsclustersResource, c.ns, name, pt, data, subresources...), &v1.HdfsCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HdfsCluster), err
}
