---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hdfs-nineinfra-tech-v1-hdfscluster
  failurePolicy: Fail
  name: mhdfscluster.kb.io
  rules:
  - apiGroups:
    - hdfs.nineinfra.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hdfsclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hdfs-nineinfra-tech-v1-hdfscluster
  failurePolicy: Fail
  name: vhdfscluster.kb.io
  rules:
  - apiGroups:
    - hdfs.nineinfra.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hdfsclusters
  sideEffects: None
