# permissions for end users to view hdfsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hdfscluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hdfs-operator
    app.kubernetes.io/part-of: hdfs-operator
    app.kubernetes.io/managed-by: kustomize
  name: hdfscluster-viewer-role
rules:
- apiGroups:
  - hdfs.nineinfra.tech
  resources:
  - hdfsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hdfs.nineinfra.tech
  resources:
  - hdfsclusters/status
  verbs:
  - get
