---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hdfs.nineinfra.tech
  resources:
  - hdfsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hdfs.nineinfra.tech
  resources:
  - hdfsclusters/finalizers
  verbs:
  - update
- apiGroups:
  - hdfs.nineinfra.tech
  resources:
  - hdfsclusters/status
  verbs:
  - get
  - patch
  - update
